#!/bin/sh
curl -L https://tljh.jupyter.org/bootstrap.py \
 | sudo python3 - \
 --show-progress-page \
 --admin ${username} \

export BASE=/opt/tljh/user/bin

add-apt-repository ppa:deadsnakes/ppa -y
apt install python3.8 python3.8-venv -y

python3.8 -m venv /opt/tljh/venv
/opt/tljh/venv/bin/pip install viewser views-stepshift ipykernel

sed -i 's_python_/opt/tljh/venv/bin/python_g' /opt/tljh/user/share/jupyter/kernels/python3/kernel.json
